@startuml

class User {
  LoginName
  Password
}
class Device {
  MsgTopic
}
class Place {
  Description
}
class MqttConnectionConfiguration{
  String brokerHost; // mqtt.dioty.co
  Int brokerPort; // 1883
  Int brokerWebSocketsPort; // (Optional) 8080
  String userId; // (Optional)
  String password; // (Optional)
  String rootTopic; // (Optional)
}

User -right- MqttConnectionConfiguration
User -down- Place
Place - Place
User -down- Device
Place -left- Device

@enduml
