@startuml
actor User
component FrontEnd
component BackEnd
component MQTT_Broker
database DataBase
cloud Cloud as C1
cloud Cloud as C2
cloud Cloud as C3
cloud Cloud as C4
agent Device

User -right- C1
C1 -right- FrontEnd
FrontEnd -right- C2
C2 -right- BackEnd  
BackEnd -right- DataBase
BackEnd -down- C3
C3 -left- MQTT_Broker
MQTT_Broker -left- C4
C4 -left- Device
@enduml
