@startuml
hide footbox
title Log in to the application
actor User
entity Frontend
entity Backend
database Database
entity MQTT_Broker
User -> Frontend: Authentication Request
Frontend -> Backend: Authentication Request
activate Backend
Backend -> Database: Query User table
Database -> Backend: Query result
Backend -> Database: Query Place, Device, Connection tables
Database -> Backend: Query result
Backend -> MQTT_Broker : Authentication Request
MQTT_Broker  -> Backend : Authentication Response
Backend -> MQTT_Broker : Subscribe Request
MQTT_Broker  -> Backend : Subscribe Response
Backend -> Frontend: Authentication Response
deactivate Backend
Frontend -> User: Authentication Response
@enduml