@startuml
hide footbox
title User sends a command to a device
actor User
entity Frontend
entity Backend
entity MQTT_Server
User -> Frontend: Send command Request
Frontend -> Backend: Send command Request
activate Backend
Backend -> MQTT_Server : Publish Request
MQTT_Server  -> Backend : Publish Response
Backend -> Frontend: Send command Response
deactivate Backend
Frontend -> User: Send command Response
@enduml