@startuml
hide footbox
title User receives a command from a device

actor User
entity Frontend
entity Backend
entity MQTT_Broker

MQTT_Broker -> Backend: Send command
Backend -> Backend: Processes command
Backend -> Frontend: Update information Request
Frontend -> User: Updated information
@enduml